name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_ORG: "evandjefie"
  IMAGE_NAME: "myreactjs-portfolio"
  IMAGE_TAG: "1.0.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_ORG/$IMAGE_NAME:$IMAGE_TAG .
          docker tag $DOCKER_ORG/$IMAGE_NAME:$IMAGE_TAG $DOCKER_ORG/nom_du_projet:$IMAGE_TAG

#      - name: Log in to Docker Hub
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        

      - name: Push Docker image
        run: |
          docker push $DOCKER_ORG/$IMAGE_NAME:latest
          docker push $DOCKER_ORG/nom_du_projet:$IMAGE_TAG
